platform :ios, '9.0'
use_frameworks!

target 'ANZBreadcrumbsNavigationController_Example' do
  pod 'ANZBreadcrumbsNavigationController', :path => '../'

  target 'ANZBreadcrumbsNavigationController_Tests' do
    inherit! :search_paths
  end
end
